### ISSUE TITLE
Java implementation for MaterialX

### ISSUE THREAD

**Issue by hendrikebbers** [materialx/MaterialX#148]
Hi all,
is a Java implementation for MaterialX planed for the future or are you interested in such a project?

Thanks,

Hendrik

**Comment by jstone-lucasfilm** [comment]
Hi Hendrik,

Our team isn't currently planning a Java implementation, but we'd have no objection to your starting one if you have a compelling use case in mind!

All the best,

-Jonathan

**Comment by jstone-lucasfilm** [comment]
I'll close this issue for now, and feel free to follow up on the MaterialX forum if you'd like to continue the discussion:

https://groups.google.com/forum/#!forum/materialx
