### ISSUE TITLE
Python module: Error loading

### ISSUE THREAD

**Issue by nyue** [materialx/MaterialX#2]
I managed to build on OS X but have problem importing the Python module

Anyone having success on Windows or CentOS to verify if this is OS specific ?

Cheers
----log output----
(materialx-env) Nicholass-MacBook:build-gcc nicholas$ python
Python 2.7.10 (default, Jul 14 2015, 19:46:27) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import MaterialX
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nicholas/projects/MaterialX/materialx-env/lib/python2.7/site-packages/MaterialX/__init__.py", line 1, in <module>
    from MaterialX.main import *
  File "/Users/nicholas/projects/MaterialX/materialx-env/lib/python2.7/site-packages/MaterialX/main.py", line 3, in <module>
    from MaterialX.PyMaterialX import *
ImportError: No module named PyMaterialX

**Comment by jstone-lucasfilm** [comment]
Hi Nicholas!  It's possible that you've found a real build issue, as we regularly build MaterialX Python across the matrix of Windows/Linux and Python 2.6/2.7, but we rely upon feedback from external developers on OSX.  Let us know if you (or another member of the OSX development community) discover the source of the issue, and feel free to propose a fix.

**Comment by selfshadow** [comment]
After some digging around, it appears that Python can load the library binaries if they're *.so, rather than *.dylib.

@nyue: try adding the following lines to `source/PyMaterialX/CMakeLists.txt` (then run `cmake` etc. again):

```
if (APPLE)
set_target_properties(
    PyMaterialX
    PROPERTIES
    SUFFIX
    .so)
endif()
```
Hopefully that does the trick.

**Comment by nyue** [comment]
Confirm that the suffix was the issue.
I have not submitted a CLA yet so I won't do a pull request for the above.
I will do so next week when I get back to work and have access to a scanner for the CLA submission, if no one else beat me to that :-)

Cheers

**Comment by jstone-lucasfilm** [comment]
Thanks Nicholas!  Just to follow up on this thread, we've started the process of implementing this change at Lucasfilm, and we plan to submit a pull request once it's been vetted.

**Comment by rutajoshi** [comment]
@selfshadow and @nyue - I'm having the same issue, but adding the set_target_properties line doesn't seem to work. PyMaterialX isn't recognized as a target. How did you resolve this issue, if you ran into it?
