### ISSUE TITLE
Compilation problems on OSX

### ISSUE THREAD

**Issue by robpieke** [materialx/MaterialX#205]
It looks like `<cstdlib>` gets included via `<algorithm>` on Linux but not OSX, which is (for me at least) resulting in a failed compilation on my Macbook.

A possible fix:

```
diff --git a/source/MaterialXFormat/Environ.cpp b/source/MaterialXFormat/Environ.cpp
index 4a9ef04..529af29 100644
--- a/source/MaterialXFormat/Environ.cpp
+++ b/source/MaterialXFormat/Environ.cpp
@@ -7,6 +7,8 @@
 
 #include <MaterialXCore/Util.h>
 
+#include <cstdlib>
+
 #if defined(_WIN32)
 #define WIN32_LEAN_AND_MEAN
 #include <windows.h>
diff --git a/source/MaterialXRender/ImageHandler.h b/source/MaterialXRender/ImageHandler.h
index 4f83626..9e79f62 100644
--- a/source/MaterialXRender/ImageHandler.h
+++ b/source/MaterialXRender/ImageHandler.h
@@ -14,6 +14,7 @@
 #include <cmath>
 #include <map>
 #include <array>
+#include <cstdlib>
 
 #include <MaterialXFormat/File.h>
 
```

**Comment by jstone-lucasfilm** [comment]
Many thanks for this detailed report, Rob.  If there are OSX targets where <cstdlib> is not brought into Library.h through other standard headers, then it seems appropriate for us to explicitly include <cstdlib> in Library.h as well.

If we were to move forward with that approach, then the fix would simply be the addition of a <cstdlib> include just after <algorithm> in Library.h.

**Comment by robpieke** [comment]
Yep, abandoning my previous suggestion in favour of adding to `Library.h` works as well (I've tested this).

```
diff --git a/source/MaterialXCore/Library.h b/source/MaterialXCore/Library.h
index 125fdb2..5459ccb 100644
--- a/source/MaterialXCore/Library.h
+++ b/source/MaterialXCore/Library.h
@@ -18,6 +18,7 @@
 #include <string>
 #include <unordered_map>
 #include <vector>
+#include <cstdlib>
 
 namespace MaterialX
 {
```

**Comment by jstone-lucasfilm** [comment]
Thanks for the report, and this should be addressed in the latest master.
