### ISSUE TITLE
Connecting an input directly to an output doesn't generate correct GLSL code

### ISSUE THREAD

**Issue by laserallan** [materialx/MaterialX#217]
I have a nodegraph/nodedef looking like this:
```
  <nodedef name="ND_MtlxShader" type="color3" node="MtlxShader">
    <input name="banan" type="color3" value=" 1.000000, 0.047582, 0.000000" uifolder="Material Inputs" />
  </nodedef>
  <nodegraph name="inputs" nodedef="ND_MtlxShader" type="color3">
    <output name="baseColor_output" type="color3" interfacename="banan" />
  </nodegraph>
```
I.E the output is directly connected to an input using interface name.
When I generate GLSL from it I get something like this:
void inputs(vec3 banan, out vec3 baseColor_output)
```
void inputs(vec3 banan, out vec3 baseColor_output)
{
    baseColor_output = vec3(0.0);
}

```
If I introduce a node doing nothing between the input and the output it works.
```
  <nodedef name="ND_MtlxShader" type="color3" node="MtlxShader">
    <input name="banan" type="color3" value=" 1.000000, 0.047582, 0.000000" uifolder="Material Inputs" />
  </nodedef>
  <nodegraph name="inputs" nodedef="ND_MtlxShader" type="color3">
    <output name="baseColor_output" type="color3" nodename="node_1350078633" />
    <add name="node_1350078633" type="color3">
      <input name="in1" type="color3" interfacename="banan" />
      <input name="in2" type="color3" value=" 0.000000, 0.000000, 0.000000" />
    </add>
  </nodegraph>
```
Now the generated code looks like this:
```
void inputs(vec3 banan, out vec3 baseColor_output)
{
    const vec3 node_1350078633_in2_tmp = vec3(0.000000, 0.000000, 0.000000);
    vec3 node_1350078633_out = banan + node_1350078633_in2_tmp;
    baseColor_output = node_1350078633_out;
}
```

I would think this is a bug. If not, is there a way of connecting an input to an output directly and should there be an error when validating things if doing it the way I did?

**Comment by niklasharrysson** [comment]
Hi David,

Thanks for the feedback! Using `interfacename` directly on an output is not supported by the specification, it can only be used on inputs/parameters. It seems the validation fails to detect this. 

We could either allow it in the spec and add support for it to shader generation, or fix the validation to report this as invalid. For a spec change we should discuss further with Lucasfilm.

In the mean time a simple workaround is to use a constant node in between:
```
  <nodedef name="ND_MtlxShader" type="color3" node="MtlxShader">
    <input name="banan" type="color3" value=" 1.000000, 0.047582, 0.000000" uifolder="Material Inputs" />
  </nodedef>
  <nodegraph name="inputs" nodedef="ND_MtlxShader" type="color3">
    <constant name="dummy" type="color3">
      <parameter name="value" type="color3" interfacename="banan"/>
    </constant>
    <output name="baseColor_output" type="color3" nodename="dummy" />
  </nodegraph>
````
which produce the following shader code:
```
void inputs(vec3 banan, out vec3 baseColor_output)
{
    vec3 dummy_out = banan;
    baseColor_output = dummy_out;
}
```

**Comment by laserallan** [comment]
Thanks for the information. I'll use that for now.

**Comment by jstone-lucasfilm** [comment]
Good catch, thanks David!  My sense is that this case should be caught in validation, as Niklas suggests above, and I'll add a note that we need to make this amendment.  I've leave this issue open until the change has been made.

**Comment by jstone-lucasfilm** [comment]
Thanks for the report, and this validation warning has been added.
