### ISSUE TITLE
MaterialXView: Object space position doesn't do anything meaningful since obj files don't support transforms

### ISSUE THREAD

**Issue by laserallan** [materialx/MaterialX#231]
Would it be possible to make object space positions to be normalized by the bounding box of the object or similar so it's possible to make materials with noises that are not completely dependent on the scene size.

**Comment by jstone-lucasfilm** [comment]
I like this suggestion of a "normalized object" space in MaterialX, but I believe it's still important to maintain a distinction between this and traditional object space.  Even though the MaterialX viewer doesn't currently interpret object and world space differently, it's likely to do so in the future (as support for additional geometric formats and scene descriptions come online), and it will be important to maintain consistency in our interpretation of these spaces with other renderers supporting MaterialX.

**Comment by laserallan** [comment]
It's a good point. Maybe the right solution is to look at a different file format don't want to go down the path of checkboxes for all of this.
