### ISSUE TITLE
getValue() for floatarray type inputs

### ISSUE THREAD

**Issue by Sosoyan** [materialx/MaterialX#291]
I'm having an error when calling input object's getValue() method, if the type is floatarray. Can't see anything about this type in the class index docs either?

<input name="position" type="floatarray" value="0.886555, 1">

AttributeError: 'MaterialX.PyMaterialXCore.Value' object has no attribute 'getData'

**Comment by jstone-lucasfilm** [comment]
Good catch, and it looks like we still need to add Python bindings for the array type value accessors.  This should be a straightforward extension of existing logic, though we’ll need special handling for Python lists and tuples of values.

**Comment by jstone-lucasfilm** [comment]
Thanks for posting this issue, and it should now be fixed in master (#292).
