### ISSUE TITLE
Storing Node positions

### ISSUE THREAD

**Issue by Sosoyan** [materialx/MaterialX#313]
This is a question rather than an issue. I'd like to store the node positions when writing .mtlx files, so can I add an arbitrary attributes to the Nodes using the MaterialX API, as I see there are set, get, remove attribute member functions in the Node class?

**Comment by dbsmythe** [comment]
Yes, you should be able to use the normal getAttribute/setAttribute/hasAttribute member functions to get/set/check for "xpos" and "ypos" float attributes on nodes and a few other supported element types.  Please refer to the "Standard UI Attributes" section of the [Specification document](http://www.materialx.org/assets/MaterialX.v1.37.Spec.pdf) (p.45) for details on how those attribute values are interpreted.

**Comment by jstone-lucasfilm** [comment]
Closing this issue for now, but feel free to follow up with additional questions on the MaterialX discussion forum (https://groups.google.com/forum/#!forum/materialx).
