### ISSUE TITLE
[Lucasfilm] WebGL Viewer

### ISSUE THREAD

**Issue by jstone-lucasfilm** [materialx/MaterialX#344]
Implement a WebGL viewer for MaterialX content, allowing a MaterialX document to be viewed directly in the browser.

One path to this implementation would be to upgrade MaterialXView to the latest version of NanoGUI (https://github.com/mitsuba-renderer/nanogui), which supports WebGL through Emscripten.

**Comment by jstone-lucasfilm** [comment]
Adding a link to recent related work in the Autodesk fork of MaterialX:

https://github.com/autodesk-forks/MaterialX/pull/879

**Comment by meshula** [comment]
Here's a PR for updating nanogui. https://github.com/materialx/MaterialX/pull/443

**Comment by fire** [comment]
Interested in this through Godot Engine's webgl (gles2) implementation. https://github.com/godotengine/godot-proposals/issues/714 However, for simplicity, do this as a standalone :).

**Comment by jstone-lucasfilm** [comment]
This issue can now be closed, as pull request #709 adds a web viewer to the MaterialX project (https://materialx.github.io/MaterialX/).  Thanks to our colleagues at Autodesk for their great work on this feature!
