### ISSUE TITLE
Ability to use a cmake installed version of pybind11.

### ISSUE THREAD

**Issue by alister-chowdhury** [materialx/MaterialX#355]
Hello,

We'd quite like to be able to provide our own version of pybind11 (which is partially covered here #146).

Sadly, if pybind11 is made available by using a CMake install, they aren't explicit put in a `/tools` directory but instead will be placed in `/share/cmake/pybind11` etc.

as expected by:
[`list(APPEND CMAKE_MODULE_PATH "${MATERIALX_PYTHON_PYBIND11_DIR}/tools")`](https://github.com/materialx/MaterialX/blob/master/source/PyMaterialX/CMakeLists.txt#L26)

Using `find_package(pybind11)` is a pretty standard way of accessing the modules.

Would it be acceptable to change the logic such that it first searches for pybind11, before appending the path and including pybind11Tools?

**Comment by jstone-lucasfilm** [comment]
This sounds like a great proposal for a change, Alister.  Would you be open to writing a pull request for this, as you have a working CMake install of PyBind11 to test against?  You would need to sign up as a contributor to MaterialX, but the approval process should be quick.

https://github.com/materialx/MaterialX/blob/master/CONTRIBUTING.md

**Comment by alister-chowdhury** [comment]
Going to try and get the higher ups to approve it all, and will get back to you :)

**Comment by jstone-lucasfilm** [comment]
Thanks to @alister-chowdhury for adding this support in #411, and I'm closing out the original issue.
