### ISSUE TITLE
Ability to support both OIIO 1.x and 2.x

### ISSUE THREAD

**Issue by alister-chowdhury** [materialx/MaterialX#358]
Hi again,

Our main renderer for the foreseeable future seems to only support OIIO 1.x (unfortunately).
In #316 it was mentioned supporting both API's in the future was an option.

It _looks_ pretty trivial to do so, as the only file that needs changing is OiioImageLoader.cpp, and the OIIO_VERSION_MAJOR def could probably used to branch in the pre-processor.

Assuming the paper work for #355 goes through ok, would this be an acceptable solution?

**Comment by lgritz** [comment]
Don't the changes in #316 already support both OIIO 1.x and 2.x? I don't think any `#if` on the OIIO version is needed.

**Comment by jstone-lucasfilm** [comment]
Alister and Larry,

We're not yet using the recommended "auto" pattern with the two create() functions, which is recommended for code that needs to support both OIIO 1.x and 2.x:

https://github.com/OpenImageIO/oiio/wiki/OIIO-2.0-Porting-Guide

My sense is that we'd need to apply this pattern to OiioImageLoader.cpp for correctness in both versions, though Larry would know with certainty.

-Jonathan

**Comment by lgritz** [comment]
I think it might even be easier than I said in that wiki page:

    std::unique_ptr<ImageInput> in (ImageInput::open(...));

I think that's all there is to it, since you can initialize the unique_ptr in this manner whether II::open returns a raw `ImageInput*` (1.x) or returns a unique_ptr directly (2.x). It will delete when it goes out of scope, there's no need for the destroy() call.

**Comment by jstone-lucasfilm** [comment]
Thinking about this a bit further, the simplified pattern described above may not work consistently in OpenImageIO 1.x.  In this situation, the ImageInput object will be allocated on the heap in the OpenImageIO DLL, and then wrapped by a unique_ptr in client code.  When the unique_ptr goes out of scope, it will be deallocated from the _client_ heap, which is not a safe pattern in all environments (e.g. in Windows builds where the CRT is not shared between application and DLL).

**Comment by lgritz** [comment]
Ugh, you may be right. In OIIO 2.0, there's a custom deleter for these, so the memory free will definitely happen on the DLL side. But, yeah, 1.x may be messy.

The way I described it in that porting guide wiki, I think, is correct for both cases.

I do also recommend encouraging everybody to upgrade to OIIO 2.x. Anything 1.x hasn't been a supported release for a couple years now.

**Comment by jstone-lucasfilm** [comment]
Thanks for bringing this to our attention, @alister-chowdhury.  This should now be addressed in #393, and let us know how it works for you.
