### ISSUE TITLE
Is there a MaterialX DCC bridge example?

### ISSUE THREAD

**Issue by glorion13** [materialx/MaterialX#421]
Hello, this is a question rather than an issue with MaterialX.

We are looking to start building authoring support for MaterialX from within DCCs like Clarisse. Initially we are planning to start small, with some of the more fundamental things.

I was wondering if you have an example of this kind of translation between an actual DCC and MaterialX, that we could use as a reference for this work?

Thanks!

**Comment by jstone-lucasfilm** [comment]
I can think of two public MaterialX implementations that I would recommend as examples, and feel free to add others that I may have missed:

- The MaterialX plug-in for Substance Designer, which uses Python scripts to write generic graphs from Substance-specific graphs.  This seems the closest to the DCC bridge example that you're looking for.
- The Autodesk fork of MaterialX, which has a wealth of C++ examples for MaterialX shader code generation (e.g. Arnold OSL, Nvidia MDL).

Substance Designer plug-in:
https://share.substance3d.com/libraries/6111

Arnold OSL code generator:
https://github.com/autodesk-forks/MaterialX/tree/adsk_contrib/dev/source/MaterialXGenArnold

Nvidia MDL code generator:
https://github.com/autodesk-forks/MaterialX/tree/mdl/dev/source/MaterialXGenMdl

**Comment by jstone-lucasfilm** [comment]
Here's another good DCC bridge example that I was reminded of today, a sample Maya plug-in for MaterialX in the Autodesk fork:

https://github.com/autodesk-forks/MaterialX/tree/adsk_contrib/dev/source/MaterialXContrib/MaterialXMaya

**Comment by glorion13** [comment]
Those are great! Thanks, really appreciate it. :)
