### ISSUE TITLE
Baker cannot find nodedefs

### ISSUE THREAD

**Issue by bsavery** [materialx/MaterialX#468]
I have a mtlx file exported from Substance.  When trying to run through the texture baker script I get an error "LookupError: Could not find a nodedef for node 'standard_surface_constructor'".  I tried manually setting the --library or --path option to the included stdlib/stlib_defs.mtlx file.  Since I see that node defined as a "surfaceshader" and that is there.

Any ideas?
[MTL_Exports 2.zip](https://github.com/materialx/MaterialX/files/5120577/MTL_Exports.2.zip)

**Comment by jstone-lucasfilm** [comment]
Hi Brian,

Good catch, and this is an area that we're actively working on.  For now, you need to provide the baking script with a "--path" argument, pointing to the root of your MaterialX installation (e.g. "--path /projects/MaterialX").

Going forward, we'd like to begin including the standard data libraries as part of MaterialX Python, which would remove the need for that step.

All the best,

-Jonathan

**Comment by niklasharrysson** [comment]
Also, just want to mention that the nodedef you are looking for is in the
physically-based shader node library (pbrlib). The output *type* for
"standard_surface_constructor" is 'surfaceshader', which is a datatype in
stdlib, but the node definition itself, the node named <surface>, is found
in pbrlib. So make sure you load that library as well if not done already
(pbrlib/pbrlib_defs.mtlx).

Cheers,
/Niklas


Den tis 25 aug. 2020 kl 06:18 skrev Jonathan Stone <notifications@github.com

**Comment by bsavery** [comment]
So actually I think the problem here is this line:  https://github.com/materialx/MaterialX/blob/fadc2e5938b556d12f54759d1cc7f275576cd9f1/python/Scripts/baketextures.py#L42

using cwd, I was running this from outside that directory. I believe this should be something more like:

os.path.join(os.path.abspath(__file__), '..', '..')

to have that script file executable from anywhere.

**Comment by jstone-lucasfilm** [comment]
@bsavery That sounds like a good step forward, as it would allow baketextures.py to find its data libraries from the surrounding MaterialX repository.  Would you be interested in proposing that change in a pull request to MaterialX GitHub?

Going forward, we'd still like to include the stdlib/pbrlib/bxdf libraries in MaterialX Python itself, but your proposed change would remove this need in the short term.

**Comment by bernardkwok** [comment]
Couple of things that you might want to look out for.
- The Substance export includes it's own stdlib definitions so when exporting you might want to exclude them to avoid conflicts. The library load in general will load the first version found so if conflicts occur then you may need to check the search pathing order.
- Depending on where the definition libraries to point to, it seems that the texture path logic needs a bit of tweaking as well. Believe it will work to find images in folders directly under the input file name but would not find any associated with libraries.

**Comment by bsavery** [comment]
Yeah I mean I'll PR the change for the local path to the script, for the deeper ones @bernardkwok mentions about texture path logic I don't have a definite opinion on yet, so I'll leave that to later.

**Comment by jstone-lucasfilm** [comment]
If you're not running into those issues, @bsavery, then I believe your proposed script change would be a worthy improvement to the codebase.  We'll circle back to the larger topic of library/image dependencies and MaterialX Python for v1.38.

**Comment by dbsmythe** [comment]
I would suggest that MATERIALX_SEARCH_PATH should only be used to find xi:include'd .mtlx files, and should not apply to images or textures.  This is because included mtlx files will naturally come from many sources and would be maintained separately, while images are generally used directly by the rendering engine and must be located quickly and exactly.  And I would normally recommend that any search path, including MATERIALX_SEARCH_PATH, should normally start with ".:" so it would look in the current directory first.  Filenames in <image> or other nodes within a MaterialX nodegraph or shader should always be either relative to the current directory, or (much less desirably) a full path or a search query.

**Comment by jstone-lucasfilm** [comment]
Fixed in pull request #470 by @bsavery
