### ISSUE TITLE
materialXview does not respect the "default" parameter on images

### ISSUE THREAD

**Issue by koen-v** [materialx/MaterialX#484]
I believe this mtlx should show up green, but it shows up red instead, the default value on the image node is ignored. It appears correctly in the glsl though.

Thanks,
Koen

<?xml version="1.0"?>
<materialx version="1.37">
    
    <nodegraph name="defaultMix" >
        
        <image name="mask" type="float" >
            <parameter name="file" type="filename" value="i_dont_exist.png" />
            <parameter name="default" type="float" value="1.0"/>
        </image>
        
        <mix name="over" type="color3">
            <input name="bg" type="color3" value="1.0,0.0,0.0" /> 
            <input name="fg" type="color3" value="0.0,1.0,0.0" />
            <input name="mix" type="float" nodename="mask"/>
        </mix>

        <output name="colorOut" type="color3" nodename="over" />
    </nodegraph>

    <material name="Material">
        <shaderref name="Material" node="standard_surface">
            <bindinput name="base_color" type="color3"  nodegraph="defaultMix" output="colorOut" />
        </shaderref>
    </material>

</materialx>

**Comment by jstone-lucasfilm** [comment]
Thanks for bringing this to our attention, @koen-v!  This has now been addressed in pull request #520.

**Comment by koen-v** [comment]
thanks!
