### ISSUE TITLE
Build failed on Ubuntu : cannot import name 'sysconfig' from 'distutils'

### ISSUE THREAD

**Issue by johhnry** [materialx/MaterialX#501]
Hi,

I am trying to build the project on Ubuntu with the python library and the viewer but this is the error output : 

```
MaterialX/build $ cmake -DMATERIALX_BUILD_PYTHON=ON -DMATERIALX_BUILD_VIEWER=ON ..                                 
-- Using X11 for window creation
-- Using PyBind11 v2.4.3
CMake Error at source/PyMaterialX/PyBind11/tools/FindPythonLibsNew.cmake:96 (message):
  Python config failure:

  Traceback (most recent call last):

    File "<string>", line 1, in <module>

  ImportError: cannot import name 'sysconfig' from 'distutils'
  (/usr/lib/python3.7/distutils/__init__.py)

Call Stack (most recent call first):
  source/PyMaterialX/PyBind11/tools/pybind11Tools.cmake:16 (find_package)
  source/PyMaterialX/CMakeLists.txt:41 (include)


-- Configuring incomplete, errors occurred!
See also "MaterialX/build/CMakeFiles/CMakeOutput.log".
See also "MaterialX/build/CMakeFiles/CMakeError.log".
```

Most of the [links](https://github.com/pypa/pip/issues/5356) on internet suggest to do `sudo apt install python3-distutils` but it's already installed on my system.

Also those commands works properly : 

```
$ python2 -c "from distutils import sysconfig"
$ python3 -c "from distutils import sysconfig"
```

Specs : 

OS: `Linux pop-os 5.4.0-7642-generic 20.04`
python2: `2.7.18`
python3: `3.8.5`
python3-distutils: `3.8.5-1~20.04.1`

What could be the issue here?

Thanks

**Comment by jstone-lucasfilm** [comment]
When multiple Python environments are available in the system path, we've often found it necessary to provide more information to the CMake configuration process.  In our cloud-based Ubuntu tests, for example, we'll commonly add "-DMATERIALX_PYTHON_VERSION=2" or "-DMATERIALX_PYTHON_VERSION=3" to the CMake command line, just to make sure our intent is clear:

https://github.com/materialx/MaterialX/blob/master/.github/workflows/build.yml#L23

Perhaps that's worth a try in your build environment as well?

-Jonathan

**Comment by johhnry** [comment]
Hi,

Thank you for your answer. There is the same error message : 

```
MaterialX/build $ cmake -DMATERIALX_BUILD_PYTHON=ON -DMATERIALX_BUILD_VIEWER=ON -DMATERIALX_PYTHON_VERSION=3 ..
-- Using X11 for window creation
-- Using PyBind11 v2.4.3
-- Found PythonInterp: /usr/bin/python3.7 (found suitable version "3.7.5", minimum required is "3") 
CMake Error at source/PyMaterialX/PyBind11/tools/FindPythonLibsNew.cmake:96 (message):
  Python config failure:

  Traceback (most recent call last):

    File "<string>", line 1, in <module>

  ImportError: cannot import name 'sysconfig' from 'distutils'
  (/usr/lib/python3.7/distutils/__init__.py)

Call Stack (most recent call first):
  source/PyMaterialX/PyBind11/tools/pybind11Tools.cmake:16 (find_package)
  source/PyMaterialX/CMakeLists.txt:41 (include)


-- Configuring incomplete, errors occurred!
See also "MaterialX/build/CMakeFiles/CMakeOutput.log".
See also "MaterialX/build/CMakeFiles/CMakeError.log".
```

Maybe this is specific to my Python installation and Ubuntu upgrade to 20.04...

**Comment by jstone-lucasfilm** [comment]
Yes, that's starting to look more likely -- that there's an issue with the Python environment itself.  Perhaps a reinstall will do the trick?

**Comment by jstone-lucasfilm** [comment]
I'll close out this issue for now, @johhnry, and feel free to bring up any additional build questions on the MaterialX forum (https://groups.google.com/g/materialx).
