### ISSUE TITLE
Ignoring CMAKE_DEBUG_POSTFIX

### ISSUE THREAD

**Issue by debaetsd** [materialx/MaterialX#504]
It seems that the current cmake setup is ignoring `CMAKE_DEBUG_POSTFIX` in favor of `MATERIALX_DEBUG_POSTFIX`.

I had to add an special MaterialX-only case to my build pipeline as all other dependencies in my setup (OSL/OpenExr/... ) do follow the built-in cmake `CMAKE_DEBUG_POSTFIX` variable.

I understand that this is a trivial issue with a clean and proper workaround though imho there is also no reason the keep the custom `MATERIALX_DEBUG_POSTFIX`.

I can help by making the needed code changes/PRs if there is consensus here that this should be changed.

**Comment by jstone-lucasfilm** [comment]
This sounds like a good change to me, @debaetsd, and I'd be open to your writing up a PR.

@bernardkwok Would you have any concerns about this from the Autodesk side?

**Comment by jstone-lucasfilm** [comment]
This has been addressed by @debaetsd in pull request #509.
