### ISSUE TITLE
Compile-time option to disable exceptions

### ISSUE THREAD

**Issue by boberfly** [materialx/MaterialX#512]
Hello,

Just an idea looking through the codebase with plans to bring it into a game engine/runtime environment. Perhaps MaterialX needs a compile-time option added which removes runtime exceptions? Game engines tend to frown upon using them.

Notable examples:
SPIRV-Cross
https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_cross_error_handling.hpp
PugiXML
https://github.com/materialx/MaterialX/blob/master/source/MaterialXFormat/PugiXML/pugiconfig.hpp#L30

Just to note it's awesome seeing Library.h alias containers, makes it simple to swap out with another one eg. EASTL that's good.

Cheers!

**Comment by jstone-lucasfilm** [comment]
Hi @boberfly, this sounds like a reasonable proposal to me, and I could imagine a wrapper mechanism similar to the one in SPIR-V, where a library-wide helper function selects between throwing exceptions and exiting the program with an error message.

If we took this approach in MaterialX, we would likely want to add an Exception.h header to MaterialXCore, which would define the appropriate wrapper functions and include <exception> only when required.

Let us know how your plans proceed, and we'd be open to a pull request if you find that you need the ability to disable exceptions in your runtime.

**Comment by boberfly** [comment]
Hi @jstone-lucasfilm 

I've already started something similar to what SPIRV-Cross is doing locally here. I'll see how I go time-wise and propose a PR. Currently it is a bunch of macros everywhere and modifying MaterialXCore/Library.h, but I only modified the modules that were needed eg. Core/Format/GenGlsl/GenShader so far. 

I'll continue with this with a test project to see how it works in practice.

Cheers

**Comment by fire** [comment]
How is the progress on removing exceptions? This is still important for game engines like Godot Engine.

(This was in the wrong thread.)

**Comment by boberfly** [comment]
Hi @fire actually I have it in a scratch branch here on my machine but unfortunately didn't continue on with it due to other commitments. I can push what I have to my fork when I get around to it if you'd like, so it's not wasted work.

Cheers

**Comment by fire** [comment]
@boberfly Thanks for your offer.

This is a notification! \o\

**Comment by jstone-lucasfilm** [comment]
@boberfly I'm going to close out this issue for now, but it sounds like a good feature proposal, and feel free to revisit this issue if you have the bandwidth to move it forward.
