### ISSUE TITLE
Python Module - loading error

### ISSUE THREAD

**Issue by Kaiz3rTool** [materialx/MaterialX#593]
Hello,
I've build MaterialX on Centos7, using cmake3, with success but when I want to deals with the python module, I have some errors:
`from .PyMaterialXCore import *
ModuleNotFoundError: No module named 'MaterialX.PyMaterialXCore'`

I have checked in the folder, the file doesn't exist at all. same thing for the PyMaterialXFormat file. I only have this : 
![image](https://user-images.githubusercontent.com/4272733/108023311-8eaf8a80-7022-11eb-8bad-5f68da914f21.png)

I have trtied to build with no options changed, then in activating the MATERIALX_BUILD_PYTHON option, same result

I can't use the prebuild version for now as centos7 use older GLIB

how can I fix it please ?

**Comment by jstone-lucasfilm** [comment]
Hello!

Looking at that folder, I believe you need to build the "install" target when you're building the MaterialX project in CMake.  Here's an example of how to build the install target, from our cloud-based tests for MaterialX C++/Python:

https://github.com/materialx/MaterialX/blob/master/.github/workflows/main.yml#L126

That should create the full installation of MaterialX Python, which contains both the pure Python wrappers (seen in your folder) and the platform-specific binaries that provide the low-level functionality for MaterialX.

**Comment by Kaiz3rTool** [comment]
hello @jstone-lucasfilm, thank you for your help,
sorry I'm not able to make it work (I have a poor build level sadly)
If I compile with turning MATERIALX_BUILD_PYTHON to ON

`cmake3 CMakeLists.txt
cmake3 --build . --target install`

I have an error : 
`[ 74%] Building CXX object source/PyMaterialX/PyMaterialXCore/CMakeFiles/PyMaterialXCore.dir/PyDefinition.cpp.o
In file included from /mnt/Pipeline/Toolset/BUILD/MaterialX-1.37.4/source/PyMaterialX/PyBind11/include/pybind11/pytypes.h:12:0,
                 from /mnt/Pipeline/Toolset/BUILD/MaterialX-1.37.4/source/PyMaterialX/PyBind11/include/pybind11/cast.h:13,
                 from /mnt/Pipeline/Toolset/BUILD/MaterialX-1.37.4/source/PyMaterialX/PyBind11/include/pybind11/attr.h:13,
                 from /mnt/Pipeline/Toolset/BUILD/MaterialX-1.37.4/source/PyMaterialX/PyBind11/include/pybind11/pybind11.h:44,
                 from /mnt/Pipeline/Toolset/BUILD/MaterialX-1.37.4/source/PyMaterialX/PyBind11/include/pybind11/operators.h:12,
                 from /mnt/Pipeline/Toolset/BUILD/MaterialX-1.37.4/source/PyMaterialX/../PyMaterialX/PyMaterialX.h:24,
                 from /mnt/Pipeline/Toolset/BUILD/MaterialX-1.37.4/source/PyMaterialX/PyMaterialXCore/PyDefinition.cpp:6:
/mnt/Pipeline/Toolset/BUILD/MaterialX-1.37.4/source/PyMaterialX/PyBind11/include/pybind11/detail/common.h:112:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.
gmake[2]: *** [source/PyMaterialX/PyMaterialXCore/CMakeFiles/PyMaterialXCore.dir/PyDefinition.cpp.o] Error 1
gmake[1]: *** [source/PyMaterialX/PyMaterialXCore/CMakeFiles/PyMaterialXCore.dir/all] Error 2
gmake: *** [all] Error 2
`
I have also tried with the --config release option, it gives the same result
I have tried with both master folder (i guess 1.38) and 1.37.4 release, both fails at the same step

**Comment by Kaiz3rTool** [comment]
hello @jstone-lucasfilm, thank you for your help,
sorry I'm not able to make it work (I have a poor build level sadly)
If I compile with  MATERIALX_BUILD_PYTHON to ON
then
```
export PYTHON_INCLUDE_DIR=/usr/local/include/python2.7
export PYTHON_LIBRARY=/usr/lib64/libpython2.7.so

cmake3 CMakeLists.txt
cmake3 --build . --target install
```
compiling and build seems to goes fine, but I still not have the PyMaterialXCore and PyMaterialXFormat in the python folder

**Comment by Kaiz3rTool** [comment]
hello, 
just find that it doesn't work on my network drive, but no problem in local for some reasons
sorry for the noise

bests

**Comment by jstone-lucasfilm** [comment]
No worries, and glad you figured it out!
