### ISSUE TITLE
No way to find version of lib at compile-time

### ISSUE THREAD

**Issue by pmolodo** [materialx/MaterialX#704]
I could not find a way to detect at compile-time which version of the MaterialX library I'm linking against.  (At runtime, I can use `getVersionIntegers()` and `getVersionString()` defined in Util.h.)

It would be nice if there were a generated `version.h` file generated using cmake's `configure_file` function (or similar), from a `version.h.in`:

```
#define MATERIALX_MAJOR_VERSION @MATERIALX_MAJOR_VERSION@
#define MATERIALX_MINOR_VERSION @MATERIALX_MINOR_VERSION@
#define MATERIALX_BUILD_VERSION @MATERIALX_BUILD_VERSION@
```

**Comment by jstone-lucasfilm** [comment]
This is a great suggestion, thanks @pmolodo.  We'll plan to add this feature in MaterialX v1.38.3.

**Comment by jstone-lucasfilm** [comment]
This pull request has been merged, and let us know how it works out for you.  Although it still won't be possible to test for MaterialX versions prior to v1.38.3 at compile time, it should now be possible to test for all future MaterialX versions through this mechanism.
