### ISSUE TITLE
materialx libs galore: individual meaning and monolithic option

### ISSUE THREAD

**Issue by pberto** [materialx/MaterialX#705]
If I build materialx I see a target of... 10 dynamic libraries. 

I would like to know: 

1. is there a description of what each library is required for?

- Core: self explanatory
- Format: ?
- GenGlsl/Mdl/Osl: self explanatory
- GenShader: ?
- Render: see below
- RenderGlsl/Hw/Osl: self explanatory, but do you also need the previous Render one? 

2. is there a way to compile a "monolithic" single MaterialX library rather than having 10 individual libs on disk?

**Comment by bernardkwok** [comment]
HI Paolo,

For 1.
- There is some here: https://github.com/materialx/MaterialX/tree/main/source but could probably be made more robust. 

For the Gen* and Render* libraries the un-postfixed libraries are the base or core logic on which shading language 
variants are built on top of.

- Shader generation has it's own technical document.  This would explain the basics behind GenShader. https://github.com/materialx/MaterialX/blob/main/documents/DeveloperGuide/ShaderGeneration.md which could
probably use some cross referencing

For 2. There is no current configuration option to do so, but I suppose such a one could be accomplished by adding a
"Material All" config. It has this split currently to allow flexibility, and the integration can pull in the libs desired.
Any dynamic libraries mirros the current lib structure.

**Comment by pberto** [comment]
All clear, thanks Bernard. This can be closed.
