### ISSUE TITLE
Shader code generated by MaterialX is not deterministic

### ISSUE THREAD

**Issue by vlasovi** [materialx/MaterialX#710]
In the shader code generated by MaterialX some functions may go in an arbitrary (random) order, meaning that if I do two or more attempts to generate the shader from the same document, I will get two or more diffently assembled shaders.

This issue prevents proper hashing of MaterialX shaders by their source code in USD's HdStorm, causing a huge performance penalty due to constant shader recompilations.

Having debugged the issue I found it's source:

- Function ShaderGraph::topologicalSort outputs '_nodeOrder' array which is not deterministic.
- The reason for that is on line 1216 of file ShaderGraph.cpp: "for (const auto& input : output->getConnections())"
- output->getConnections() is effectively std::set<ShaderInput*>, so it is sorted by pointer address which is not deterministic
- And so the loop itself adds nodes in a non-deterministic order, which results in non-deterministic shader source code in the end

**Comment by jstone-lucasfilm** [comment]
Thanks to @niklasharrysson for addressing this in #767, and to @vlasovi for reporting this important issue!
