### ISSUE TITLE
MaterialXView: version 1.38.2: compile error on macOS: context.getShaderGenerator().getTarget()

### ISSUE THREAD

**Issue by jasonliu--** [materialx/MaterialX#741]
Greetings, I'm the creator and maintainer of the [MaterialX package](https://ports.macports.org/port/materialx/details/) for the [MacPorts package management system](https://www.macports.org/). I've been trying to package version 1.38.2, and I keep getting a compile error when the build gets to MaterialXView. This error appears to be new, and wasn't present in MaterialX 1.38.1.

Here's the error from the build log:
```
:info:build [ 82%] Building CXX object source/MaterialXView/CMakeFiles/MaterialXView.dir/Material.cpp.o
:info:build cd /opt/local/var/macports/build/_ports_graphics_materialx/materialx/work/build/source/MaterialXView && /usr/bin/clang++
            -DMATERIALX_BUILD_GEN_GLSL -DMATERIALX_BUILD_GEN_MDL -DMATERIALX_BUILD_GEN_OSL -DMATERIALX_BUILD_OIIO
            -DMATERIALX_INSTALL_MDL_MODULE_PATH=\"\" -DMATERIALX_MDLC_EXECUTABLE=\"\" -DMATERIALX_MDL_MODULE_PATHS=\"\"
            -DMATERIALX_MDL_RENDER_ARGUMENTS=\"\" -DMATERIALX_MDL_RENDER_EXECUTABLE=\"\"
            -DMATERIALX_OSL_INCLUDE_PATH=\"/opt/local/share/OSL/shaders\" -DMATERIALX_TESTOSLC_EXECUTABLE=\"/opt/local/bin/oslc\"
            -DMATERIALX_TESTRENDER_EXECUTABLE=\"/opt/local/bin/testrender\" -DMATERIALX_TEST_RENDER
            -I/opt/local/include -I/opt/local/include/eigen3 -I/opt/local/include/nanovg
            -I/opt/local/var/macports/build/_ports_graphics_materialx/materialx/work/MaterialX-1.38.2/source/MaterialXFormat/..
            -I/opt/local/var/macports/build/_ports_graphics_materialx/materialx/work/MaterialX-1.38.2/source/MaterialXCore/..
            -I/opt/local/var/macports/build/_ports_graphics_materialx/materialx/work/MaterialX-1.38.2/source/MaterialXGenGlsl/..
            -I/opt/local/var/macports/build/_ports_graphics_materialx/materialx/work/MaterialX-1.38.2/source/MaterialXGenShader/..
            -I/opt/local/var/macports/build/_ports_graphics_materialx/materialx/work/MaterialX-1.38.2/source/MaterialXRenderGlsl/..
            -I/opt/local/var/macports/build/_ports_graphics_materialx/materialx/work/MaterialX-1.38.2/source/MaterialXRenderHw/..
            -I/opt/local/var/macports/build/_ports_graphics_materialx/materialx/work/MaterialX-1.38.2/source/MaterialXGenOsl/..
            -I/opt/local/var/macports/build/_ports_graphics_materialx/materialx/work/MaterialX-1.38.2/source/MaterialXGenMdl/..
            -pipe -isystem /Users/jasonliu/ports/graphics/materialx/files/old_appkit_compat -Os -DNDEBUG
            -I/opt/local/include -stdlib=libc++ -arch x86_64 -mmacosx-version-min=10.11 -fPIE -Wall -Wno-missing-braces
            -std=gnu++11 -MD -MT source/MaterialXView/CMakeFiles/MaterialXView.dir/Material.cpp.o
            -MF CMakeFiles/MaterialXView.dir/Material.cpp.o.d
            -o CMakeFiles/MaterialXView.dir/Material.cpp.o
            -c /opt/local/var/macports/build/_ports_graphics_materialx/materialx/work/MaterialX-1.38.2/source/MaterialXView/Material.cpp
:info:build /opt/local/var/macports/build/_ports_graphics_materialx/materialx/work/MaterialX-1.38.2/source/MaterialXView/Material.cpp:79:56:
            error: no viable conversion
            from 'const string' (aka 'const basic_string<char, char_traits<char>, allocator<char> >')
            to 'const MaterialX::ShaderGenerator'
:info:build     _hasTransparency = mx::isTransparentSurface(_elem, context.getShaderGenerator().getTarget());
:info:build                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
:info:build /opt/local/include/MaterialXGenShader/ShaderGenerator.h:29:24:
            note: candidate constructor (the implicit copy constructor) not viable: no known conversion
            from 'const string' (aka 'const basic_string<char, char_traits<char>, allocator<char> >')
            to 'const MaterialX::ShaderGenerator &' for 1st argument
:info:build class MX_GENSHADER_API ShaderGenerator
:info:build                        ^       
:info:build /opt/local/include/MaterialXGenShader/ShaderGenerator.h:184:5:
            note: candidate constructor not viable: no known conversion
            from 'const string' (aka 'const basic_string<char, char_traits<char>, allocator<char> >')
            to 'SyntaxPtr' (aka 'shared_ptr<MaterialX::Syntax>') for 1st argument
:info:build     ShaderGenerator(SyntaxPtr syntax);
:info:build     ^
:info:build /opt/local/include/MaterialXGenShader/Util.h:35:87: note: passing argument to parameter 'shadergen' here
:info:build MX_GENSHADER_API bool isTransparentSurface(ElementPtr element, const ShaderGenerator& shadergen);
:info:build                                                                                       ^       
:info:build 1 error generated.
:info:build make[2]: *** [source/MaterialXView/CMakeFiles/MaterialXView.dir/Material.cpp.o] Error 1
```

**Comment by jstone-lucasfilm** [comment]
@jasonliu-- That's an interesting one, and it looks like you may have a stale header file in `/opt/local/include/MaterialXGenShader/Util.h`.

The debug output above mentions that the interface of `isTransparentSurface` is `bool isTransparentSurface(ElementPtr element, const ShaderGenerator& shadergen)`, but the latest codebase has a different interface for that function:

https://github.com/materialx/MaterialX/blob/main/source/MaterialXGenShader/Util.h#L35

**Comment by jasonliu--** [comment]
> @jasonliu-- That's an interesting one, and it looks like you may have a stale header file in `/opt/local/include/MaterialXGenShader/Util.h`.
> 

Theoretically, that shouldn't be possible. When we do our package development, all MacPorts packagers are instructed to completely delete _everything_ related to any previous builds, and force MacPorts to do a completely clean build from scratch (using the `port clean materialx` command). Every time a software package is built from source by way of a completely clean build, the MacPorts build system actually fetches the zipped up source code tarball directly from the `Releases` section of the project's GitHub website. So unless the `Util.h` header file is stale in your released tarballs in your `Releases` section, the MacPorts build would be using whatever `Util.h` file is included in the 1.38.2 tarball.

> The debug output above mentions that the interface of `isTransparentSurface` is `bool isTransparentSurface(ElementPtr element, const ShaderGenerator& shadergen)`, but the latest codebase has a different interface for that function:
> 
> https://github.com/materialx/MaterialX/blob/main/source/MaterialXGenShader/Util.h#L35

As far as I can tell, that is indeed what is in the `Util.h` file that's included in the 1.38.2 release tarball. If we assume that my MacPorts builds are in fact using the 1.38.2 `Util.h` file, then what else could be causing the compile error?

**Comment by jasonliu--** [comment]
> @jasonliu-- That's an interesting one, and it looks like you may have a stale header file in `/opt/local/include/MaterialXGenShader/Util.h`.
> 

It seems that the MacPorts build system is referencing the `Util.h` file that is coming from MaterialX 1.38.1. Theoretically, the MacPorts build environment is supposed to quarantine any new "build from source" builds from anything that is already existing from any currently-installed previous versions of a package, but there have been rare instances of certain software projects that somehow "break out" of the quarantined build environment, and still attempt to directly reference already-installed files located in `/opt/local`.

I will try completely uninstalling MaterialX 1.38.1 and see whether it helps to resolve the compile error. I will report back my results.

> The debug output above mentions that the interface of `isTransparentSurface` is `bool isTransparentSurface(ElementPtr element, const ShaderGenerator& shadergen)`, but the latest codebase has a different interface for that function:
> 
> https://github.com/materialx/MaterialX/blob/main/source/MaterialXGenShader/Util.h#L35

Yes, this appears to be what is in the `Util.h` header file that is included in the MaterialX 1.38.2 tarball. Theoretically, MacPorts is supposed to conduct the builds using on only the files from the source code tarball (hence why you see all of those `-I/opt/local/var/macports/build/_ports_graphics_materialx/materialx/work/MaterialX-1.38.2/source/blahblah` lines in the build log), but echoing what I said above, ill-behaved source code does sometimes find a way to break out of the build environment. It's quite possible that it's subtly related to the wider discussion that I triggered regarding possible hard-coding of certain paths that is being discussed in #728.

**Comment by jstone-lucasfilm** [comment]
Let us know what you find on your side, @jasonliu--, and we're interested in the proposed improvements to installation paths in #728 as well.

**Comment by jasonliu--** [comment]
Reporting back. Completely removing MaterialX 1.38.1 does indeed resolve the error, and 1.38.2 now builds fine without any further issues.

What this tells me is that there does indeed seem to be something in MaterialX's build files that is able to break out of MacPorts' quarantined build environment. Probably some path(s) that is/are "hard-coded", although hard-coded is a misnomer, since I highly doubt you guys are actually writing anything like `/opt/local`. Instead, there are probably some CMake variables in one or more `CMakeLists.txt` file(s) which are somehow resolving to be `/opt/local`, instead of `/opt/local/var/macports/build/_ports_graphics_materialx/materialx/work/MaterialX-1.38.2/source` (i.e. the build folder). I have no idea where it might be happening, but it's probably something to keep an eye out for as you work on the codebase.

@jstone-lucasfilm , thanks for the help. Your reply message was exactly the extra pair of eyes that finally allowed me get the newest MaterialX packaged. :thumbsup:

Feel free to close this issue.

P.S.: Completely unrelated to the issue.... I'm not sure whether you noticed, but if you look at the [MaterialX package](https://ports.macports.org/port/materialx/details/) page on our website, you will see that I have builds of MaterialX (including the Viewer) working all the way back to macOS 10.9 Mavericks, even though your code technically only compiles back to macOS 10.12 Sierra. MacPorts has modules in it that allow for some pretty surprising legacy support, and we packagers can be somewhat stubborn about trying to get the latest software to successfully compile on older systems. So if the MaterialX devs ever get questions about running MaterialX on older Macs, feel free to send those inquiries our way! :smiley:

**Comment by jstone-lucasfilm** [comment]
Thanks @jasonliu--, and it's great to see the extended macOS support for MaterialX!  I'll close out this issue for now, and we can continue the discussion of installation improvements on the related tickets.
