### ISSUE TITLE
Can't generate OSL shaders for .mtlx files not included in original libraries

### ISSUE THREAD

**Issue by Hoover2h** [materialx/MaterialX#746]
Hello,

I am trying to generate OSL shader source code from a .mtlx file using the materialX.cpp program attached here as .txt file I think. After performing some tests, I have determined that it works on .mtlx files included in the libraries folder of this repo such as standard_surface.mtlx but not on SimpleSrf.mtlx which is an example file I found on MaterialX's website. I attached it here as a .txt as well. I am fairly certain I have positioned directories properly for loadLibraries to function properly. I change the node def on line 39 to whatever I want each time. When it doesn't work, it will crash on line 53 (generating the shader pointer). Any help is greatly appreciated, thanks.
[materialX.txt](https://github.com/materialx/MaterialX/files/7487813/materialX.txt)
[SimpleSrf.txt](https://github.com/materialx/MaterialX/files/7487846/SimpleSrf.txt)

**Comment by kwokcb** [comment]
HI there,

The files in `Materials/Examples/Syntax` are meant to show syntax examples and for the most part don't necessarily have any shader code implementations. Mostly likely it's throwing an exception indicating such. If you catch exceptions then you can see the message.

 - Materials/Examples/[StandardSurface|USDPreviewSurface] are using library definition which have implementations.
 - Materials/TestSuite/ has a number of files also using library definitions with implementations.
 
 These files are checked as part of the unit test suite.
 
 Hope this helps.

**Comment by jstone-lucasfilm** [comment]
Thanks to @Hoover2h for this question, and I believe @kwokcb covers the most important details in his answer above.

One additional link that may be worthwhile is the `generateshaders.py` script, which is used to generate OSL shaders from MaterialX examples in our test suite:

https://github.com/materialx/MaterialX/blob/main/python/Scripts/generateshader.py

As Bernard notes, the examples in the `Materials/Examples/Syntax` folder are not renderable, but examples in folders such as `Materials/Examples/StandardSurface` and `Materials/Examples/UsdPreviewSurface` should work smoothly.

I'll close out this issue for now, and feel free to join the discussion in our ASWF Slack if you have other questions about the API or example materials:

https://www.materialx.org/DiscForum.html
