### ISSUE TITLE
configure doesn't look for nanogui and compilation then can't find nanovg.h

### ISSUE THREAD

**Issue by yurivict** [materialx/MaterialX#751]
configure should properly discover all required dependencies.

This flag ```CSSFLAGS=-I${LOCALBASE}/include/nanogui``` needs to be added for compilation to succeed.

**Comment by jstone-lucasfilm** [comment]
This sounds like a reasonable proposal to me, @yurivict, though I could use more clarity on the details of the change.  Would you be interested in writing up a pull request that makes the specific edit you propose?

**Comment by jstone-lucasfilm** [comment]
It doesn't sound like we have enough details to address this issue, so I'll close it out for now, but feel free to reopen the issue with more details in the future.
