### ISSUE TITLE
undefined reference to MaterialX::GLContext::GLContext

### ISSUE THREAD

**Issue by yurivict** [materialx/MaterialX#752]
The current revision 0f94298 fails:
```
ld: error: source/MaterialXRenderGlsl/libMaterialXRenderGlsl.so.1.38.3: undefined reference to MaterialX::GLContext::GLContext(std::__1::shared_ptr<MaterialX::SimpleWindow>, __GLXcontextRec*) [--no-allow-shlib-undefined]
```

**Comment by jstone-lucasfilm** [comment]
@yurivict Can you provide more details on the operating system and compiler you're building with?  So far, we're seeing successful building, testing, and rendered results with this specific revision of MaterialX main:

https://github.com/materialx/MaterialX/actions/runs/1446033189

But there are certainly operating systems and compilers that we don't yet (or can't yet) include in our build matrix, and we're interested in ideas on how to extend it further going forward.

**Comment by yurivict** [comment]
The compiler is clang-12. Did you test with clang?

**Comment by jstone-lucasfilm** [comment]
Yes, we include Clang 9, 11, and 12 in our build matrix, and here's a link to the build output for Clang 12:

https://github.com/materialx/MaterialX/runs/4170571805?check_suite_focus=true

**Comment by yurivict** [comment]
What about MATERIALX_BUILD_VIEWER? Is it on during tests?

**Comment by jstone-lucasfilm** [comment]
For all configurations in our build matrix, we build with MATERIALX_BUILD_VIEWER set to ON.  (You can see all of these details in the links above, including the specific command line options set for each build.)

**Comment by jstone-lucasfilm** [comment]
I'll close out this issue for now, and let us know if you learn more details about the situations in which this build error occurs.  Since we don't yet have support for FreeBSD builds in our GitHub Actions matrix, we'd appreciate any insights into fixes that would address build issues on that platform.
