### ISSUE TITLE
Allow build to set custom namespace

### ISSUE THREAD

**Issue by kwokcb** [materialx/MaterialX#773]
To avoid possible clashes, it has been recommended to allow for custom namespace setting.
Currently MaterialX has a hard-coded name space but this could be settable via a Cmake option
as is done for OCIO. Then each integration can set it's own namespace to help avoid clashes if MaterialX
is pulled in via multiple integrations.

Note that this could be a possible avenue to avoid things like global symbol clashes as mentioned in #772.

This is a check-in in OCIO repo for namespace setting:
https://github.com/AcademySoftwareFoundation/OpenColorIO/commit/b3f6e9d1dd22b7b86bdcd2820c4e6a69b353ad9e
Note: that namespace can also be used to encode version so the API entry points can be versioned:
https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/main/CMakeLists.txt#L203-L214

**Comment by jstone-lucasfilm** [comment]
Thanks for posting this issue, @kwokcb, and it's been resolved in #785.
