### ISSUE TITLE
Python 3 Bindings

### ISSUE THREAD

**Issue by lvxejay** [materialx/MaterialX#8]
Any plans for Python 3 support? What would be necessary to generate the proper python bindings for this library?

**Comment by jstone-lucasfilm** [comment]
I think this is a great idea, and I believe it should be a relatively straightforward improvement to make to MaterialX.

The core library on which the PyMaterialX module is based (PyBind11) already natively supports Python 3.x, so the main work would be resolving the two changes we've made to PyBind11 for MaterialX, which are listed below:

- We've extended PyBind11 to support Python 2.6 (natively it only supports Python 2.7 and above).
- We've added a compile-time flag (PYBIND11_PREFER_PYINT) which allows the developer to choose whether Python methods using integers should prefer objects of Python type 'int' or 'long'.

So far, these two extensions have only been built and unit tested with Python 2.x, so a developer would need to build PyMaterialX with Python 3.x and resolve any issues that come up.

Additionally, the handful of pure-Python wrappers in python/MaterialX would need to be updated for compatibility with Python 3 syntax.

**Comment by lvxejay** [comment]
I've tried building this for Python 3.5.2 using the provided "Quick Start Guide" for developers. However, running setup.py results in a "package not found" error. Is there more specific documentation for how to get this library setup and working properly?

**Comment by jstone-lucasfilm** [comment]
Python 3 is now supported, but let us know if you encounter any issues with MaterialX in this environment, since the majority of our testing at Lucasfilm is with Python 2.x.
