### ISSUE TITLE
LookupError: Could not find a matching implementation for node 'surfacematerial' matching target 'genglsl'

### ISSUE THREAD

**Issue by c0ffymachyne** [materialx/MaterialX#804]
Hi,
I am trying to generate a shader from code used in test cases and xml generates fine but I am getting below error:

```
shader = shadergen.generate(shaderNodeName, shaderNodes[0], context)
LookupError: Could not find a matching implementation for node 'surfacematerial' matching target 'genglsl'
```

I presume it is related to below part of the code:

```
    # Create a simple shader interface.
    simpleSrf = doc.addNodeDef('', 'surfaceshader', 'simpleSrf')
    simpleSrf.setInputValue('diffColor', mx.Color3(1.0))
    simpleSrf.setInputValue('specColor', mx.Color3(0.0))
    roughness = simpleSrf.setInputValue('roughness', 0.25)
    roughness.setIsUniform(True);
    
    # Instantiate shader and material nodes.
    shaderNode = doc.addNodeInstance(simpleSrf)
    materialNode = doc.addMaterialNode('', shaderNode)
```

I did try manipulating the paths but it then does not find code for other nodes.

**Comment by c0ffymachyne** [comment]
```
  <nodegraph name="nodegraph1" fileprefix="folder/" colorspace="lin_rec709">
    <constant name="node1" type="color3">
      <input name="value" type="color3" value="0.1, 0.2, 0.3" />
    </constant>
    <image name="node2" type="color3">
      <input name="file" type="filename" value="image1.tif" />
    </image>
    <output name="output1" type="color3" nodename="node1" />
    <output name="output2" type="color3" nodename="node2" />
    <turbulence3d name="turbulence1" type="float">
      <input name="octaves" type="integer" value="5" />
    </turbulence3d>
  </nodegraph>
  <nodedef name="nodeDef1" node="turbulence3d">
    <output name="out" type="float" />
    <input name="octaves" type="integer" value="3" />
    <input name="lacunarity" type="float" value="2" />
    <input name="gain" type="float" value="0.5" />
  </nodedef>
  <nodedef name="nodedef1" node="simpleSrf">
    <output name="out" type="surfaceshader" />
    <input name="diffColor" type="color3" value="1, 1, 1" />
    <input name="specColor" type="color3" value="0, 0, 0" />
    <input name="roughness" type="float" value="0.25" uniform="true" />
  </nodedef>
  <simpleSrf name="node1" type="surfaceshader" nodedef="nodedef1">
    <input name="diffColor" type="color3" output="output1" nodegraph="nodegraph1" />
    <input name="roughness" type="float" value="0.5" />
  </simpleSrf>
  <surfacematerial name="node2" type="material">
    <input name="surfaceshader" type="surfaceshader" nodename="node1" />
  </surfacematerial>
</materialx>
```

**Comment by kwokcb** [comment]
Are you taking this from the Syntax folder https://github.com/materialx/MaterialX/tree/main/resources/Materials/Examples/Syntax ?
It has been noted that these are syntax only examples and don't have any shader implementations for the custom types there (e.g. `simpleSrf`). The idea is to fix these up in an upcoming release.

Please look at the `Examples/StandardSurface | UsdPreviewSurface`
or `Examples/TestSuite` which has a lot of files there (is the unit test suite) 

If your looking for adding in custom source implementations then it's worth noting that additional source code paths can be added via these interfaces which can be set before generating code:
https://github.com/materialx/MaterialX/blob/main/source/MaterialXGenShader/GenContext.h#L52-L61

**Comment by c0ffymachyne** [comment]
Hi Bernard, 
Thank you for your reply. I am trying to generate a shader code on the fly so my input is going to be graph representing shading network in my application. My line of action was to traverse my graph and compose MaterialX NodeGraph dynamically and then output GLSL code straight into the OpenGL part of it. This is because I need to expose all the operators to the user and perhaps at the end, I can output mtlx file with the graph description based on nodes user connected together.

**Comment by c0ffymachyne** [comment]
Thank you for help, I managed to build connections dynamically and generate correct code.
