### ISSUE TITLE
Add python binding for Element.getDescendant

### ISSUE THREAD

**Issue by pmolodo** [materialx/MaterialX#812]
When exploring the python bindings recently, I was surprised to find no binding for `Element.getDescendant` - which I think would be a very useful method from a scripting perspective.

**Comment by kwokcb** [comment]
Probably just an oversight. Unfortunately there isn't currently an automated way to check for parity between C++ and Python interfaces. Generally when updating an API, a quick scan to update all missing wrappers is done.
If you have any suggestions on detecting this (without manual scanning) it would be great to know.

[ Also this will gives it parity with Javascript bindings :). ]

**Comment by jstone-lucasfilm** [comment]
Fixed in pull request #813, thanks @pmolodo!
