### ISSUE TITLE
Methods Missing From LighHandler in Python

### ISSUE THREAD

**Issue by c0ffymachyne** [materialx/MaterialX#818]
Hi There,

Running below command...
```
import MaterialX.PyMaterialXRender as mx_render
light_handler = mx_render.LightHandler.create()
for i in dir(light_handler):
     print(i)

```
Gives the following output...

```
__...__
addLightSource
computeLightIdMap
create
findLights
getEnvIrradianceMap
getEnvRadianceMap
getLightIdentifierMap
getLightSources
registerLights
setEnvIrradianceMap
setEnvRadianceMap
setLightSources
```

although, PyMaterialXRender does have all methods listed:

https://github.com/materialx/MaterialX/blob/3f86b1222e2b82036ea9a86fd9eeaa53c518c1c8/source/PyMaterialX/PyMaterialXRender/PyLightHandler.cpp#L17

Am I missing something (except for the methods...)?

**Comment by kwokcb** [comment]
I get this, from current head of `main`. This is on Windows in case it makes any difference.
```
addLightSource
computeLightIdMap
create
findLights
getAlbedoTable
getDirectLighting
getEnvIrradianceMap
getEnvRadianceMap
getEnvSamples
getFirstLightOfCategory
getIndirectLighting
getLightIdMap
getLightSources
getLightTransform
registerLights
setAlbedoTable
setDirectLighting
setEnvIrradianceMap
setEnvRadianceMap
setEnvSamples
setIndirectLighting
setLightSources
setLightTransform
```

**Comment by c0ffymachyne** [comment]
That is interesting. I am on Ubuntu 20.04. Is there anything that might have cause this ? I am on latest release tag. is it safe to use latest main ?

**Comment by kwokcb** [comment]
It should be, but I don't think anything has changed here for a long while though. 
Wondering if it's a PyBind11 issue on Linux as a wild guess. (Unfortunately I don't have a Linux box to try out.)

**Comment by c0ffymachyne** [comment]
Thanks, rebuilding from scratch helped.
