### ISSUE TITLE
Match of geometry used for GLSL testing and OSL testing

### ISSUE THREAD

**Issue by kwokcb** [materialx/MaterialX#822]
The geometry for the obj sphere loaded for GLSL testing does not exactly match that produced for OSL testing (testrender).
It is desirable to have this to do image compares. UV differ slighting (+ has  V-flip resulting in a V-flip for textures bound) and tangents differ quiet a bit.
![texcoord1_output_glsl](https://user-images.githubusercontent.com/49369885/151256802-388e8b9a-9418-4703-8734-2453ff64d6b6.png)
![texcoord1_output_osl](https://user-images.githubusercontent.com/49369885/151256814-f5c4e885-5fd5-4682-8d9e-bc913bbaa7d9.png)
![tangent_output_glsl](https://user-images.githubusercontent.com/49369885/151256827-4cdb4045-ee87-4157-a9c3-1710c9c3b14c.png)
![tangent_output_osl](https://user-images.githubusercontent.com/49369885/151256836-9c353951-5e33-4db9-aa86-df0dc97eb747.png)

**Comment by jstone-lucasfilm** [comment]
Thanks for this report, @bernardkwok, and the last of these mismatches has been addressed in PR #844.
